services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      - LOG_PATH=/backend/logs/
    volumes:
      - ./backend/logs:/backend/logs
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
