services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "1013:8000"
    env_file:
      - app/.env
    environment:
      - LOG_PATH=/app/logs/
    volumes:
      - ./app/logs:/app/logs
